- BAIDU_TRANSLATE_CLIENT_ID=foAIGL40ZOCv2lrZhnRQ1QCf
- ENABLE_QINIU=true
- ENABLE_RECORD_SERVICES=true
- ENABLE_REDIS=true
- ENABLE_TULING_ROBOT=true
- QINIU_ACCESS_KEY=DKGr6URLzvjjfiG0M55N9LM3X3S-FF4zoirJPaPL
- QINIU_SECRET_KEY=qRlx8GbHGPQ_2iOcjJxcjyB1cdAb3p0Cb4mucaDA
- RECORD_SERVICES_URL_PREFIX=http://kk17-tomcat2.daoapp.io/coolcantonese/services
- TULING_ROBOT_API_KEY=49e360f21ac952f40ca476b988f45e20
- WECHAT_TOKEN=R1A5ZtDqm7OrpFa9xPKsu
